// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDZg4hmtqrtxZTtgwbp0nBd2ZA-IJYHlA',
    appId: '1:93618104323:web:38e31feae2f257000fc636',
    messagingSenderId: '93618104323',
    projectId: 'myworkers-12eaa',
    authDomain: 'myworkers-12eaa.firebaseapp.com',
    databaseURL: 'https://myworkers-12eaa-default-rtdb.firebaseio.com',
    storageBucket: 'myworkers-12eaa.firebasestorage.app',
    measurementId: 'G-E5GT6LFTVN',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLwX5JP9xIkDFZgE4fGWEpkCsSB1GQO1w',
    appId: '1:93618104323:ios:c6700ff02a552dde0fc636',
    messagingSenderId: '93618104323',
    projectId: 'myworkers-12eaa',
    databaseURL: 'https://myworkers-12eaa-default-rtdb.firebaseio.com',
    storageBucket: 'myworkers-12eaa.firebasestorage.app',
    iosBundleId: 'com.example.myWorkersApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDZg4hmtqrtxZTtgwbp0nBd2ZA-IJYHlA',
    appId: '1:93618104323:web:a80cf6c4cd5aec4e0fc636',
    messagingSenderId: '93618104323',
    projectId: 'myworkers-12eaa',
    authDomain: 'myworkers-12eaa.firebaseapp.com',
    databaseURL: 'https://myworkers-12eaa-default-rtdb.firebaseio.com',
    storageBucket: 'myworkers-12eaa.firebasestorage.app',
    measurementId: 'G-HZKMFQMM3M',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLwX5JP9xIkDFZgE4fGWEpkCsSB1GQO1w',
    appId: '1:93618104323:ios:c6700ff02a552dde0fc636',
    messagingSenderId: '93618104323',
    projectId: 'myworkers-12eaa',
    databaseURL: 'https://myworkers-12eaa-default-rtdb.firebaseio.com',
    storageBucket: 'myworkers-12eaa.firebasestorage.app',
    iosBundleId: 'com.example.myWorkersApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Yf2GREOS20w-eev5em79ONrZg5UUIqQ',
    appId: '1:93618104323:android:301e22a0c76278d40fc636',
    messagingSenderId: '93618104323',
    projectId: 'myworkers-12eaa',
    databaseURL: 'https://myworkers-12eaa-default-rtdb.firebaseio.com',
    storageBucket: 'myworkers-12eaa.firebasestorage.app',
  );

}